### ISSUE TITLE
Node.js 10 and 12 support

### ISSUE THREAD

**Issue by exoego** [exoego/scala-js-nodejs#10]
Overhaul modules

- [x] Assert in #48 
- [x] Buffer in #19 
- [x] Child Processes #47 
- [x] Cluster in #49
- [x] Console in #14
- [x] Crypto in #68
- [x] DNS in #69 
- [x] <del>Domain</del> It is [pending deprecated](https://nodejs.org/api/domain.html) so dropped support in this repo.
- [x] Errors in #50 
- [x] Events in #73
- [x] File System in #58
- [x] Globals in #91
- [x] HTTP in #80
- [x] HTTP/2 in #83
- [x] HTTPS in #80
- [x] Net in #84
- [x] OS in #61
- [x] Path in #70 
- [x] Process in #72 
- [x] Query String in #62
- [x] Readline in #74 
- [x] REPL in #74 
- [x] Stream in #81 
- [x] String Decoder in #67
- [x] Timers in #63
- [x] TLS/SSL in #87
- [x] TTY in #82
- [x] UDP/Datagram in #76
- [x] URL in #90 
- [x] Utilities in #51 
- [x] VM in #86
- [x] Zlib in #89
