### ISSUE TITLE
Support Node.js 14

### ISSUE THREAD

**Issue by exoego** [exoego/scala-js-nodejs#221]
- [x] [Assert](https://nodejs.org/dist/latest-v14.x/docs/api/assert.html) Only experimental class added, so skipped (See #225)
- [x] [Buffer](https://nodejs.org/dist/latest-v14.x/docs/api/buffer.html) No updates
- [x] [Child Process](https://nodejs.org/dist/latest-v14.x/docs/api/child_process.html) in #226
- [x] [Cluster](https://nodejs.org/dist/latest-v14.x/docs/api/cluster.html) in #226
- [x] [Console](https://nodejs.org/dist/latest-v14.x/docs/api/console.html) in #228
- [x] [Crypto](https://nodejs.org/dist/latest-v14.x/docs/api/crypto.html) in #229 
- [x] [DNS](https://nodejs.org/dist/latest-v14.x/docs/api/dns.html) in #230
- [x] [Domain](https://nodejs.org/dist/latest-v14.x/docs/api/domain.html) Deprecated and not supported in this repo
- [x] [Errors](https://nodejs.org/dist/latest-v14.x/docs/api/errors.html) in #236
- [x] [Events](https://nodejs.org/dist/latest-v14.x/docs/api/events.html) in #237
- [x] [fs](https://nodejs.org/dist/latest-v14.x/docs/api/fs.html) in #238 
- [x] [HTTP](https://nodejs.org/dist/latest-v14.x/docs/api/http.html) in #239
- [x] [HTTP/2](https://nodejs.org/dist/latest-v14.x/docs/api/http2.html) in #241
- [x] [HTTPS](https://nodejs.org/dist/latest-v14.x/docs/api/https.html) in #242
- [x] [module](https://nodejs.org/dist/latest-v14.x/docs/api/modules.html) in #243
- [x] [Net](https://nodejs.org/dist/latest-v14.x/docs/api/net.html) No updates
- [x] [OS](https://nodejs.org/dist/latest-v14.x/docs/api/os.html) in #256 
- [x] [Path](https://nodejs.org/dist/latest-v14.x/docs/api/path.html) No updates
- [x] [Performance Timing API](https://nodejs.org/dist/latest-v14.x/docs/api/perf_hooks.html) in #257
- [x] [querystring](https://nodejs.org/dist/latest-v14.x/docs/api/querystring.html) No updates
- [x] [Readline](https://nodejs.org/dist/latest-v14.x/docs/api/readline.html) in #258 
- [x] [REPL](https://nodejs.org/dist/latest-v14.x/docs/api/repl.html) in #265
- [x] [Stream](https://nodejs.org/dist/latest-v14.x/docs/api/stream.html) in #267
- [x] [String Decoder](https://nodejs.org/dist/latest-v14.x/docs/api/string_decoder.html) No updates
- [x] [Timers](https://nodejs.org/dist/latest-v14.x/docs/api/timers.html) No updates
- [x] [TLS (SSL)](https://nodejs.org/dist/latest-v14.x/docs/api/tls.html) in #268
- [x] [TTY](https://nodejs.org/dist/latest-v14.x/docs/api/tty.html) No updates
- [x] [dgram](https://nodejs.org/dist/latest-v14.x/docs/api/dgram.html) in #269 
- [x] [URL](https://nodejs.org/dist/latest-v14.x/docs/api/url.html) No updates
- [x] [Util](https://nodejs.org/dist/latest-v14.x/docs/api/util.html) #224 
- [x] [V8](https://nodejs.org/dist/latest-v14.x/docs/api/v8.html) No updates
- [x] [vm](https://nodejs.org/dist/latest-v14.x/docs/api/vm.html) in #270
- [x] [Worker Threads](https://nodejs.org/dist/latest-v14.x/docs/api/worker_threads.html) in #271
- [x] [Zlib](https://nodejs.org/dist/latest-v14.x/docs/api/zlib.html) No updates

**Comment by exoego** [comment]
Closing as resolved
